name: "Daily Integration"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          git clone https://gitlab.com/soapbox-pub/soapbox-fe .

      - name: "Install Node toolchain"
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: "Build Soapbox-FE package"
        env:
          NODE_ENV: production
        run: |
          yarn
          yarn build
          mv static soapbox
          tar -zcvf soapbox.tar.gz soapbox

      - name: "Upload Soapbox-FE package"
        uses: actions/upload-artifact@v2
        with:
          name: soapbox
          path: soapbox.tar.gz

  package:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: "Unpack Soapbox-FE package"
        uses: actions/download-artifact@v2
        with:
          name: soapbox

      - name: "Prepare Soapbox-FE for deployment"
        shell: bash
        run: |
          tar -zxvf soapbox.tar.gz -C /tmp
          mkdir innereq
          xargs -n1 cp -pr /tmp/soapbox <<< "innereq/soap.sect.sunbutt.faith"
          mv innereq.json innereq/soap.sect.sunbutt.faith/instance/soapbox.json
          mv innereq_about innereq/soap.sect.sunbutt.faith/instance/about

      - name: "Upload Soapbox-FE package for Inner Equestria"
        uses: actions/upload-artifact@v2
        with:
          name: soapbox-innereq
          path: innereq

  deploy:
    runs-on: ubuntu-latest

    needs: package

    steps:
      - name: "Unpack Soapbox-FE package for Inner Equestria"
        uses: actions/download-artifact@v2
        with:
          name: soapbox-innereq

      - name: "Deploy Soapbox-FE to Inner Equestria"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CI_DEPLOYER_SSH_ADDRESS_INNEREQ }}
          username: ${{ secrets.CI_DEPLOYER_SSH_USER }}
          key: ${{ secrets.CI_DEPLOYER_SSH_KEY_INNEREQ }}
          port: ${{ secrets.CI_DEPLOYER_SSH_PORT }}
          source: soap.sect.sunbutt.faith
          target: /srv/http/soap.sect.sunbutt.faith
          strip_components: 1
          rm: true
